# Generated by Django 3.1.2 on 2020-11-16 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
                ('especialidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nompro', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elmedico', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elpaciente', to='Gestion.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('pago', models.CharField(max_length=40)),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elpacientep', to='Gestion.pacientes')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elvendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('LE', models.CharField(max_length=2)),
                ('CE', models.CharField(max_length=2)),
                ('IZ', models.CharField(max_length=2)),
                ('DE', models.CharField(max_length=2)),
                ('MA', models.CharField(max_length=2)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elnrodelpedido', to='Gestion.pedidoproductos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elprodelpedido', to='Gestion.productos')),
            ],
        ),
    ]
